version: '3.9'
services:
  tenrikufe_web:
    container_name: tenrikufe_web
    volumes:
      - ./:/var/www/html/project/tenriku.fe
    build:
      dockerfile: ./docker/web/Dockerfile
    tty: true  # ← これがないとコンテナにログインできない
    ports:
      - 8080:80
    env_file:
      - .env.dev
    environment:
      - "TZ=Japan"
    networks:
      - default
      - tenichi
networks:
  tenichi:
    external: true
